In [ ]:
import pandas as pd 
from pathlib import Path 
from datetime import datetime


DIR_PATH = Path.cwd().parent
DATA_PATH = DIR_PATH / "database"

df = pd.read_csv(DATA_PATH / "ventas_datastore.csv")

df

,id_orden,fecha,producto,categoria,precio_unitario,cantidad,canal,ciudad,metodo_pago,total_venta,fecha_str
0,1001,2024-11-23,Gorra snapback,Accesorios,17474.01,4.0,Shopify,Santiago,Transferencia,69896.04,23/11/2024
1,1002,2024-02-27,Gorra snapback,Accesorios,16218.56,5.0,MercadoLibre,Madrid,Tarjeta crédito,81092.80,27/02/2024
2,1003,2024-01-13,Gorra snapback,Accesorios,19404.71,3.0,WooCommerce,Córdoba,Transferencia,58214.13,13/01/2024
3,1004,2024-05-20,Remera básica,Ropa,14058.47,5.0,Tiendanube,Mendoza,Transferencia,70292.35,20/05/2024
4,1005,2024-05-05,Vestido floral,Ropa,36894.45,5.0,WooCommerce,Bogotá,Efectivo,184472.25,05/05/2024
...,...,...,...,...,...,...,...,...,...,...,...
5095,4602,2024-08-19,Short deportivo,Ropa,21004.67,5.0,MercadoLibre,Rosario,Efectivo,105023.35,19/08/2024
5096,1008,2024-02-22,Remera básica,Ropa,13754.23,3.0,WooCommerce,Buenos Aires,Efectivo,41262.69,22/02/2024
5097,3915,2024-07-08,Cinturón cuero,Accesorios,24780.33,3.0,MercadoLibre,Mar del Plata,Efectivo,74340.99,08/07/2024
5098,3957,2024-05-13,Gorra snapback,Accesorios,18051.12,4.0,Tiendanube,Córdoba,Tarjeta crédito,72204.48,13/05/2024
5099,1533,2024-06-09,Gorra snapback,Accesorios,17595.48,2.0,WooCommerce,Lima,Tarjeta débito,35190.96,09/06/2024

In [ ]:
df.head(10)

,id_orden,fecha,producto,categoria,precio_unitario,cantidad,canal,ciudad,metodo_pago,total_venta,fecha_str
0,1001,2024-11-23,Gorra snapback,Accesorios,17474.01,4.0,Shopify,Santiago,Transferencia,69896.04,23/11/2024
1,1002,2024-02-27,Gorra snapback,Accesorios,16218.56,5.0,MercadoLibre,Madrid,Tarjeta crédito,81092.80,27/02/2024
2,1003,2024-01-13,Gorra snapback,Accesorios,19404.71,3.0,WooCommerce,Córdoba,Transferencia,58214.13,13/01/2024
3,1004,2024-05-20,Remera básica,Ropa,14058.47,5.0,Tiendanube,Mendoza,Transferencia,70292.35,20/05/2024
4,1005,2024-05-05,Vestido floral,Ropa,36894.45,5.0,WooCommerce,Bogotá,Efectivo,184472.25,05/05/2024
5,1006,2024-04-24,Zapatillas running,Calzado,78222.74,2.0,MercadoLibre,Bogotá,Transferencia,156445.48,24/04/2024
6,1007,2024-03-12,Cinturón cuero,Accesorios,24960.23,3.0,MercadoLibre,Bogotá,Tarjeta débito,74880.69,12/03/2024
7,1008,2024-02-22,Remera básica,Ropa,13754.23,3.0,WooCommerce,Buenos Aires,Efectivo,41262.69,22/02/2024
8,1009,2024-12-12,Zapatillas running,Calzado,85243.42,3.0,WooCommerce,Mar del Plata,Efectivo,255730.26,12/12/2024
9,1010,2024-10-06,Buzo hoodie,Ropa,51190.82,5.0,Shopify,Rosario,Tarjeta crédito,255954.10,06/10/2024

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5100 entries, 0 to 5099
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_orden         5100 non-null   int64
 1   fecha            5100 non-null   str
 2   producto         5051 non-null   str
 3   categoria        5100 non-null   str
 4   precio_unitario  5100 non-null   float64
 5   cantidad         5084 non-null   float64
 6   canal            5050 non-null   str
 7   ciudad           5050 non-null   str
 8   metodo_pago      5050 non-null   str
 9   total_venta      5100 non-null   float64
 10  fecha_str        5100 non-null   str
dtypes: float64(3), int64(1), str(7)
memory usage: 806.4 KB

In [ ]:
df.describe()

          id_orden  precio_unitario     cantidad    total_venta
count  5100.000000      5100.000000  5084.000000    5100.000000
mean   3494.282549     37580.999666     2.975020  115495.648447
std    1443.942078     24468.884357     1.458578   97763.959457
min    1001.000000     -4775.121138    -1.000000    7207.580000
25%    2242.750000     17579.802500     2.000000   42105.187500
50%    3492.500000     30835.780000     3.000000   81110.985000
75%    4742.250000     54322.122500     4.000000  165036.780000
max    6000.000000     93495.010000     5.000000  465717.700000

In [ ]:
df.isnull().sum()

id_orden            0
fecha               0
producto           49
categoria           0
precio_unitario     0
cantidad           16
canal              50
ciudad             50
metodo_pago        50
total_venta         0
fecha_str           0
dtype: int64

### Precios

In [ ]:
# Trato de precios, si los precios son menores a 0 es incorrecto, eliminar o solucionarlos.

precios_negativos = df[df["precio_unitario"] <= 0]
filas_precios_negativos = len(precios_negativos)
filas_df = len(df)


if filas_precios_negativos < (filas_df * 0.1):
    df = df[df["precio_unitario"] > 0]
    print(f"Filas descartadas: {filas_precios_negativos}")
else:
    print(f"Demasiados precios inválidos ({filas_precios_negativos} / {filas_df}). Revisar el archivo.")

Filas descartadas: 82

In [ ]:
df.shape

(5018, 11)

### Corrección datos nulos en cantidad

In [ ]:
cantidad_null_negativo = df.loc[(df["cantidad"]<=0) | (df["cantidad"].isna())]
filas_cantidad_null_negativo = len(cantidad_null_negativo)

if filas_cantidad_null_negativo < df.shape[0] * 0.1:
    df = df[df["cantidad"] > 0]
    print(f"Filas eliminadas: {filas_cantidad_null_negativo}, por elemenos nulos o negativos, menos del 10% del dataset.")
else:
    print(f"Cantidad erronea alta. ({df.shape[0] / filas_cantidad_null_negativo}), revisar el dataset.")

In [ ]:
df.shape

(4865, 11)

### Corrección nulos de productos

In [ ]:
df_productos_nulos = df.loc[df["producto"].isnull()]

In [ ]:
### valido los nombres de los productos, y hago una referencia de estos productos agrupandolos por categoria y producto y haciendo la mediana de los mismos para restar.

validos = ["Remera básica", "Jean slim", "Zapatillas running", "Campera impermeable",
           "Vestido floral", "Short deportivo", "Buzo hoodie", "Medias pack x3",
           "Gorra snapback", "Cinturón cuero"]

ref = (
    df[df["producto"].isin(validos)]
    .groupby(["categoria","producto"])["precio_unitario"]
    .median()
)

ref

categoria   producto
Accesorios  Cinturón cuero         24768.390
            Gorra snapback         17904.710
            Medias pack x3          7993.575
Calzado     Zapatillas running     84599.020
Ropa        Buzo hoodie            55303.480
            Campera impermeable    72061.300
            Jean slim              45000.420
            Remera básica          14991.310
            Short deportivo        22049.970
            Vestido floral         37931.875
Name: precio_unitario, dtype: float64

In [ ]:
# Hago un bucle for para recorrer las filas de los productos nulos, encontrar el precio de esos productos, restarles el precio con los precios de las medianas de la referencia, y los que son mas bajos (mas cercano a 0) reemplazo el nombre del producto en el nan. 

mask_invaidos = ~df["producto"].isin(validos)

for i in df[mask_invaidos].index:
    categoria = df.loc[i,"categoria"]
    precio = df.loc[i,"precio_unitario"]
    candidatos = ref.loc[categoria]
    df.loc[i,"producto"] = (candidatos - precio).abs().idxmin()

In [ ]:
df["producto"].unique()

<ArrowStringArray>
[     'Gorra snapback',       'Remera básica',      'Vestido floral',
  'Zapatillas running',      'Cinturón cuero',         'Buzo hoodie',
           'Jean slim',     'Short deportivo', 'Campera impermeable',
      'Medias pack x3']
Length: 10, dtype: str

In [ ]:

#normalizo los nombres de los productos poniendo en minusculas. 
productos_normalizado = {
    'Gorra snapback':'Gorra snapback',
    'Remera básica': 'Remera basica',
    'Vestido floral':"vestido floral",
    'Zapatillas running':'zapatillas running',
    'Cinturón cuero':"cinturon cuero",
    'Buzo hoodie' :"buzo hoodie",
    'JEAN SLIM':'Jean slim',
    'Short deportivo' : "short deportivo",
    'Medias pack x3' : "medias pack x3",
    'Campera impermeable':'campera Impermeable',
}


df["producto"] = df["producto"].replace(productos_normalizado).str.lower()

df["producto"].unique()

<ArrowStringArray>
[     'gorra snapback',       'remera basica',      'vestido floral',
  'zapatillas running',      'cinturon cuero',         'buzo hoodie',
           'jean slim',     'short deportivo', 'campera impermeable',
      'medias pack x3']
Length: 10, dtype: str

### Corrección de Canal

In [ ]:
# el canal son 50 elementos que son nulos, podemos optar por poner que se compraron en tienda fisica. 

df["canal"] = df["canal"].fillna("tienda fisica")

In [ ]:
df["canal"].isnull().sum()

np.int64(0)

### Corrección de Ciudad

In [ ]:
# Al no saber la ciudad podemos poner que desconocido

df["ciudad"] = df["ciudad"].fillna("desconocido")

In [ ]:
df["ciudad"].isnull().sum()

np.int64(0)

### Corrección de Metodo de Pago

In [ ]:
# son 50 elementos que se desconoce el metodo de pago, es el 1% del dataset, podemos optar por dropearlo.

df["metodo_pago"] = df["metodo_pago"].fillna("desconocido")

In [ ]:
df["metodo_pago"].isnull().sum()

np.int64(0)

In [ ]:
df.isnull().sum()

id_orden           0
fecha              0
producto           0
categoria          0
precio_unitario    0
cantidad           0
canal              0
ciudad             0
metodo_pago        0
total_venta        0
fecha_str          0
dtype: int64

### Conversión de fecha

In [ ]:
df["fecha"] = pd.to_datetime(df["fecha"])

In [ ]:
df.info()

<class 'pandas.DataFrame'>
Index: 4957 entries, 0 to 5099
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_orden         4957 non-null   int64
 1   fecha            4957 non-null   datetime64[us]
 2   producto         4957 non-null   str
 3   categoria        4957 non-null   str
 4   precio_unitario  4957 non-null   float64
 5   cantidad         4957 non-null   float64
 6   canal            4957 non-null   str
 7   ciudad           4957 non-null   str
 8   metodo_pago      4957 non-null   str
 9   total_venta      4957 non-null   float64
 10  fecha_str        4957 non-null   str
dtypes: datetime64[us](1), float64(3), int64(1), str(6)
memory usage: 774.7 KB

In [ ]:

for fecha in df["fecha_str"]:
    if fecha is None:
        fecha = fecha.replace("fecha_invalida")

### normalización de columnas

In [ ]:
df.columns = df.columns.str.lower().str.strip().str.replace(" ", "_")

In [ ]:
df.columns

Index(['id_orden', 'fecha', 'producto', 'categoria', 'precio_unitario',
       'cantidad', 'canal', 'ciudad', 'metodo_pago', 'total_venta',
       'fecha_str'],
      dtype='str')

### Filas duplicadas

In [ ]:
df = df.drop_duplicates()
df.shape

(4865, 11)